package com.app.myapplication;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class ConexionSQLiteHelper  extends SQLiteOpenHelper {

    final String CREAR_TABLA_FRASE = "CREATE TABLE frase (id Integer, nombre TEXT, tipo TEXT, idioma TEXT)";

    public ConexionSQLiteHelper(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase basedatos) {

        basedatos.execSQL(CREAR_TABLA_FRASE);

        //Insertar Frases Yo Nunca en English
        basedatos.execSQL("Insert into frase values (1,'I have never consumed more than 4 different types of drugs in just one night', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (2,'I have never finished in the hospital after a party', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (3,'I have never fucked being so drunk that I wasnt able to talk', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (4,'I have never vomited on someone', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (5,'I have never embarrassed others ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (6,'I have never wanted to murder someone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (7,'I have never touched someone lower limb and it was dirty ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (8,'I have never been more than 48 hours without sleeping ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (9,'I have never been more than 48 hours without sleeping', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (10,'I have never suffered from a trigger', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (11,'I have never had to buy the morning after pill ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (12,'I have never fucked wearing a costume ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (13,'I have never eaten an ass ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (14,'I have never made a threesome ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (15,'I have never been discovered masturbating myself  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (16,'I have never discovered a relative masturbating him/herself ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (17,'I have never discovered a friend having sex ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (18,'I have never had sex in a public place ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (19,'I have never had sex in the sea ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (20,'I have never had sex in a shops fitting room  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (21,'I have never had sex in a car ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (22,'I have never had sex on a motorbike', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (23,'I have never been in a orgy', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (24,'I have never been sodomized', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (25,'I have never been attracted by someone of the same sex', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (26,'I have never been attracted by someone of this group', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (27,'I have never been attracted by a teacher', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (28,'I have never been discovered being drunk when returning home ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (29,'I have never been handcuffed', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (30,'I have never been arrested by the police ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (31,'I have never stolen something of less than 100 euros ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (32,'I have never recorded myself having sex', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (33,'I have never had phone sex ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (34,'I have never had sex with someone I had just met ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (35,'I have never masturbated myself with a strange object ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (36,'I have never faked an orgasm ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (37,'I have never flirted with a friends partner ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (38,'I have never pretended to be sick not to go to work ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (39,'I have never pretended to be sick not to go to school', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (40,'I have never been attracted by a person who is more than 40 years old ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (41,'I have never stolen drinking glasses in a disco ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (42,'I have never spoken negatively about someone of this group', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (43,'I have never used sexual toys with my partner ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (44,'I have never cheated on someone  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (45,'I have never vomited in public ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (46,'I have never done an erotic dance ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (47,'I have never thought of having a surgery of my limb  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (48,'I have never fallen slept on a bench ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (49,'I have never fucked in the shower ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (50,'I have never got oral sex made in the shower ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (51,'I have never made oral sex in the shower ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (52,'I have never gone out and going back home before 12  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (53,'I have never changed my degree because I didn t know what I was doing there  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (54,'I have told a boy/ a girl that my house was free just to hace sex ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (55,'I have invited someone to watch Netflix ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (56,'I have said that I was taking an exam next week not to go party', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (57,'I have never called my ex while I was in a party', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (58,'I have never called my grandmother while I was in a party ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (59,'I have never made a private party to get high in privacy ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (60,'I have never thought of being gay or lesbian ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (61,'I have never culmed in my T-shirt  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (62,'I have never taken a pregnancy test', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (63,'I have never masturbated myself more than three times in a day ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (64,'I have never used sexual lubricant ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (65,'I have never got a compliment for my genitals', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (66,'I have never tried more than 5 postures while having sex  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (67,'I have never tried cybersex  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (68,'I have never played to pretend to be another person while having sex ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (69,'I have never screamed the name of another person while having sex  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (70,'I have never used flavoured condoms ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (71,'I have never kissed someone without knowing his/her name  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (72,'I have never watched porn with my partner ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (73,'I have never made a streaptease ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (74,'I have never got a streaptease made ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (75,'I have never been requested to lend money to a friend  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (76,'I have never asked a friend for money', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (77,'I have never hooked up with a celebrity ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (78,'I have never been vomited by someone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (79,'I have never been kicked out of my house ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (80,'I have never asked someone to shit on me ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (81,'I have never had a fight with someone of my friends group', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (82,'I have never stolen someone of my friends group', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (83,'I have never fucked with someone of my friends group', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (84,'I have never measured my limb', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (85,'I have never compared my limb with others', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (86,'I have never thought of having a surgery on my tits ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (87,'I have never told my partner that I have the menstruation not to have sex  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (88,'I have told my partner that I had a headache not to have sex with him/ her ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (89,'I have made up an excuse not to go out', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (90,'I have never thought that someone of my group is a gullible person', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (91,'I have never put a name to my genitals', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (92,'I have never been asked to cum inside ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (93,'I have never played Clash Royale', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (94,'I have never asked to be cum inside ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (95,'I have never asked for anal sex', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (96,'I have never asked my partner to have anal sex ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (97,'I have never said I wasnt going to drink again the day after the party ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (98,'I have never said I wasnt going to drink and I finished the most drunk ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (99,'I have never bought a sex toy', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (100,'I have never bought more than one thing in order not to go to the supermarket checkout with only one thing ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (101,'I have never spent a whole afternoon thinking about what to wear', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (102,'I have never looked my partners mobile phone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (103,'I have never watched hentai', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (104,'I have never uploaded a photo on Instagram being drunk', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (105,'I have never sent a nude ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (106,'I have never received a nude ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (107,'I have never changed my clothes five minutes before going out ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (108,'I have never thought that I had a problem with alcohol ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (109,'I have never gone to an important meal having a hangover', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (110,'I have never thought of having children', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (111,'I have never played Fortnite', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (112,'I have never bought something that I didnt need', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (113,'I have never ended up with my partner through the phone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (114,'I have never thought of getting back with my ex', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (115,'I have never judged someone without knowing him/ her ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (116,'I have never flirted through WhatsApp', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (117,'I have never flirted with films phrases ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (118,'I have never screamed because of a videogame', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (119,'I have never thought of becoming Youtuber ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (120,'I have never broken my mobile phone during a party  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (121,'I have never thought of going to the army ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (122,'I have never drunk beer', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (123,'I have never drunk wine ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (124,'I have never drunk vodka ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (125,'I have never drunk rum ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (126,'I have never eaten pizza  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (127,'I have never eaten tacos', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (128,'I have never smoke tobacco ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (129,'I have never smoke marijuana  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (130,'I have never eaten hallucinogenic mushrooms  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (131,'I have never had an Instagram account', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (132,'I have never had a Facebook account ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (133,'I have never had a SnapChat account', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (134,'I have never flirted with a dating app', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (135,'I have never run out of money in my telephone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (136,'I have never downloaded porn in my telephone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (137,'I have never seen porn in my telephone ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (138,'I have never searched categories in XXX webpages  ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (139,'I have never mixed different types of alcohol', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (140,'I have never lost my identity card ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (141,'I have never looked for my name on Google', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (142,'I have never looked for the average penis size ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (143,'I have never made a phone prank ', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (144,'I have never recorded myself being drunk', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (145,'I have never been fined for peeing on the street', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (146,'I have never watched a reality show', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (147,'I have never been attracted to my best friends girlfriend', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (148,'I have never read a book', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (149,'I have never playing futbol', 'YN', 'English')");
        basedatos.execSQL("Insert into frase values (150,'I have never played a Drink Games', 'YN', 'English')");
        //Reservado hasta 199

        //Insertar Frasse Yo Nunca en Español
        basedatos.execSQL("Insert into frase values (200,'Yo nunca he consumido más de 4 tipos de drogas en una noche', 'YN', 'Español')");
        //349
        basedatos.execSQL("Insert into frase values (349,'Yo nunca he consumido más de 4 tipos de drogas en una noche', 'YN', 'Español')");
        //Reservado hastas 399


        //Insertar Frases Patata Caliente en English
        basedatos.execSQL("Insert into frase values (400,'Soft drink brands', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (401,'Car brands', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (402,'The Simpsons Characters', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (403,'Cartoon', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (404,'Fast Food Brands', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (405,'Verbs', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (406,'Colors', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (407,'Footballers', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (408,'European Contries', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (409,'World capitals', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (410,'Mobile brands', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (411,'Books', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (412,'Sports', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (413,'Olympic medalists', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (414,'Racing Drivers', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (415,'Superheroes', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (416,'Foods', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (417,'Social networks', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (418,'Cities', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (419,'Numbers', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (420,'Football Teams', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (421,'Singer', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (422,'Aquatic animals', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (423,'Animals', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (424,'Series', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (425,'Netflix Series', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (426,'Films', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (427,'Actors/Actresses', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (428,'Famous', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (429,'Videogames', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (430,'Fruts', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (431,'Vegetables', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (432,'Historical figures', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (433,'Clothing brands', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (434,'Newspapers', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (435,'Clothing stores', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (436,'Construction tools', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (437,'Clothing', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (438,'Types of makeup', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (439,'TV Programs', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (440,'Movie categories', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (441,'Lenguages', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (442,'Trees', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (443,'Mountains', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (444,'Real estate', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (445,'TV Channels', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (446,'Medicines', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (447,'Elements of the periodic table', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (448,'Insects', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (449,'Ball sports', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (450,'Sauces', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (451,'Politicians', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (452,'Relative to tourism', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (453,'Table games', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (454,'Things to put in a suitcase', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (455,'Fish', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (456,'Apps', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (457,'Companies', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (458,'Supermarkets', 'PC', 'English')");
        basedatos.execSQL("Insert into frase values (459,'Countries', 'PC', 'English')");
        //Reservado hasta 499

        //Insertar Frases Patata Caliente en Español - 500
        basedatos.execSQL("Insert into frase values (500,'Marcas de Refrescos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (501,'Marcas de Coche', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (502,'Personajes de Los Simpsons', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (503,'Dibujos Animados', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (504,'Marcas de Comida Rápida', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (505,'Verbos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (506,'Colores', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (507,'Futbolistas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (508,'Países Europeos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (509,'Capitales del Mundo', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (510,'Marcas de Móviles', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (511,'Libros', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (512,'Deportes', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (513,'Medallistas Olímpicos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (514,'Pilotos de Carreras', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (515,'Superheroes', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (516,'Comidas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (517,'Redes Sociales', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (518,'Ciudades', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (519,'Números', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (520,'Equipos de Fútbol', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (521,'Cantantes', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (522,'Animales Acuaticos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (523,'Animales', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (524,'Series', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (525,'Series de Netflix', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (526,'Películas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (527,'Actores/Actrices', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (528,'Famosos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (529,'Videojuegos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (530,'Frutas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (531,'Verduras', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (532,'Personajes Históricos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (533,'Marcas de Ropa', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (534,'Periódicos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (535,'Tiendas de ropa', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (536,'Herramientas de construcción', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (537,'Prendas de vestir', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (538,'Tipos de Maquillaje', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (539,'Programas de TV', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (540,'Categorías de Películas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (541,'Idiomas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (542,'Árboles', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (543,'Montañas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (544,'Inmobiliario', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (545,'Canales de TV', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (546,'Medicamentos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (547,'Elementos de la tabla periódica', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (548,'Insectos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (549,'Deportes con pelota', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (550,'Salsas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (551,'Políticos', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (552,'Relativo al turismo', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (553,'Juegos de mesa', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (554,'Cosas que meter en una maleta', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (555,'Pescados', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (556,'Apps', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (557,'Empresas', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (558,'Supermercados', 'PC', 'Español')");
        basedatos.execSQL("Insert into frase values (559,'Países', 'PC', 'Español')");
        //Reservado hasta 599

        //Insertar Mimica en Español - 600
        basedatos.execSQL("Insert into frase values (600,'Plátano', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (601,'Papel', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (602,'Aguja', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (603,'Lento', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (604,'Abecedario', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (605,'Pokemon', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (606,'Call of Duty', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (607,'Crema', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (608,'Agua', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (609,'Pocoyo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (610,'Ibiza', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (611,'Ratón', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (612,'Lista', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (613,'Regadera', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (614,'Brad pit', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (615,'Mando', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (616,'Camarero', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (617,'Número', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (618,'Rosa', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (619,'Cuaderno', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (620,'Libro', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (621,'Europa', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (622,'Continentes', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (623,'Presidente', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (624,'Ordenador', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (625,'Botella', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (626,'Sonido', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (627,'Mario Bros', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (628,'Ballena', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (629,'Tiburon', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (630,'Llaves', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (631,'Tenedor', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (632,'Cuchillo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (633,'Ingrediente', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (634,'Colacao', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (635,'Caja', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (636,'Operación', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (637,'Camión', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (638,'Bob Esponja', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (639,'Trofeo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (640,'Medalla', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (641,'Real Madrid', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (642,'Jabón', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (643,'Taza', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (644,'Café', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (645,'John Wick', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (646,'Pimiento', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (647,'Pico', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (648,'Pala', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (649,'Corazón', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (650,'Galaxia', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (651,'Anarquía', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (652,'Manzana', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (653,'Champions League', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (654,'Los Beatles', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (655,'Spotify', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (656,'Youtube', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (657,'Bloqueo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (658,'Tiro', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (659,'Pistola', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (660,'Francia', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (661,'EEUU', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (662,'Analgésico', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (663,'Hidratación', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (664,'Fregona', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (665,'Julio', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (666,'Calendario', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (667,'17', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (668,'SpiderMan', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (669,'Codo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (670,'Rodillera', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (671,'Pintura', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (672,'Pollo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (673,'Nariz', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (674,'Blanco', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (675,'Línea', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (676,'Acueducto', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (677,'Tubería', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (678,'Elefante', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (679,'Seta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (680,'Serpiente', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (681,'Hipopótamo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (682,'Pez', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (683,'Alga', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (684,'Letra', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (685,'Perro', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (686,'Policía', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (687,'Lentejas', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (688,'Golf', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (689,'Escritorio', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (690,'App', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (691,'Interestelar', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (692,'Rey León', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (693,'Patético', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (694,'Kiwi', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (695,'Palomitas', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (696,'Cine', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (697,'Mercedes', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (698,'Patatas Fritas', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (699,'Hamburguesa', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (700,'Conmovedor', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (701,'Alquiler', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (702,'Acusado', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (703,'Cargador', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (704,'Tabla', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (705,'Lavandería', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (706,'Calle', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (707,'Vecino/a', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (708,'Jirafa', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (709,'Escuela', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (710,'Helado', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (711,'Derecho', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (712,'Billete', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (713,'Virus', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (714,'Vidrio', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (715,'Shakira', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (716,'IKEA', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (717,'Batman', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (718,'Instagram', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (719,'Mensaje', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (720,'FriendZone', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (721,'Google', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (722,'Iglesia', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (723,'Mapa', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (724,'Conservar', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (725,'TripAdvisor', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (726,'Fake News', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (727,'Buffet', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (728,'Vídeos', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (729,'Sexo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (730,'Lechuga', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (731,'Reciclar', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (732,'Texto', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (733,'Mosquito', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (734,'Guitarra', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (735,'Pandereta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (736,'Condón', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (737,'Árbol', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (738,'Planeta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (739,'Tierra', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (740,'Barriga', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (741,'Marte', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (742,'USB', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (743,'Angelina Jolie', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (744,'Cristiano Ronaldo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (745,'Boxeo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (746,'Ventana', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (747,'Microsoft', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (748,'Sol', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (749,'Luna', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (750,'Música', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (751,'Marvel', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (752,'Supermercado', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (753,'Agujero', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (754,'Leche', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (755,'Queso', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (756,'Ney York', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (757,'Cuadrado', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (758,'Peluquería', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (759,'Impresora', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (760,'Zapato', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (761,'Caos', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (762,'Parquímetro', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (763,'Llamada', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (764,'Fuego', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (765,'Gasolinera', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (766,'Anuncio', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (767,'Arcoiris', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (768,'Semáforo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (769,'Gol', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (770,'McDonalds', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (771,'Bicicleta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (772,'Luz', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (773,'Oscuridad', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (774,'Puerta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (775,'Espejo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (776,'Apuesta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (777,'LeBron James', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (778,'Mosca', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (779,'Galletas', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (780,'Araña', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (781,'Pelo', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (782,'Carta', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (783,'Cerveza', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (784,'Laboratorio', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (785,'Universidad', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (786,'Piratas del Caribe', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (787,'James Bond', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (788,'Roma', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (789,'Christopher Nolan', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (790,'Laberinto', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (791,'Inteligencia artificial', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (792,'Concurso', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (793,'Demonio', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (794,'Wi-Fi', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (795,'Sin Condón', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (796,'Ascensor', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (797,'Factura', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (798,'Mimica', 'MM', 'Español')");
        basedatos.execSQL("Insert into frase values (799,'DrinkGame', 'MM', 'Español')");
        //Reservado hasta el 799

        //Insertar Mimica en Ingles- 800
        basedatos.execSQL("Insert into frase values (800,'Banana', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (801,'Paper', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (802,'Needle', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (803,'Slow', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (804,'Alphabet', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (805,'Pokemon', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (806,'Call of Duty', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (807,'Cream', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (808,'Water', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (809,'Pocoyo', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (810,'Ibiza', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (811,'Mouse', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (812,'List', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (813,'Watering can', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (814,'Brad pit', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (815,'Controller', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (816,'Waiter', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (817,'Number', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (818,'Rose', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (819,'Notebook', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (820,'Book', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (821,'Europe', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (822,'Continents', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (823,'President', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (824,'Computer', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (825,'Bottle', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (826,'Sound', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (827,'Mario Bros', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (828,'Whale', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (829,'Shark', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (830,'Keys', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (831,'Fork', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (832,'Knife', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (833,'Ingredients', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (834,'Cocoa', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (835,'Box', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (836,'Operation', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (837,'Truck', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (838,'Bob Esponja', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (839,'Trophy', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (840,'Medal', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (841,'Real Madrid', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (842,'Soap', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (843,'Cup', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (844,'Coffee', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (845,'John Wick', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (846,'Pepper', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (847,'Peak tool', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (848,'Shovel', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (849,'Heart', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (850,'Galaxy', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (851,'Anarchy', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (852,'Apple', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (853,'Champions League', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (854,'Los Beatles', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (855,'Spotify', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (856,'Youtube', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (857,'Block', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (858,'Shoot', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (859,'Gun', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (860,'France', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (861,'EEUU', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (862,'Analgesic', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (863,'Hydration', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (864,'Mop', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (865,'July', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (866,'Calendar', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (867,'17', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (868,'SpiderMan', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (869,'Elbow', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (870,'Knee pad', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (871,'Paint', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (872,'Chicken', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (873,'Nose', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (874,'White', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (875,'Line', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (876,'Aqueduct', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (877,'Pipeline', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (878,'Elephant', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (879,'Mushroom', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (880,'Snake', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (881,'Hippopotamus', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (882,'Fish', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (883,'Alga', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (884,'Letter', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (885,'Dog', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (886,'Police', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (887,'Lentils', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (888,'Golf', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (889,'Desktop', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (890,'App', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (891,'Interestellar', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (892,'The Lion King', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (893,'Pathetic', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (894,'Kiwi', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (895,'Popcorn', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (896,'Cinema', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (897,'Mercedes', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (898,'Chips', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (899,'Hamburguer', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (900,'Soulful', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (901,'Rental', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (902,'Accused', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (903,'Charger', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (904,'Table', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (905,'Laundry', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (906,'Street', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (907,'Neighbor', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (908,'Giraffe', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (909,'School', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (910,'Ice Cream', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (911,'Right', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (912,'Ticket', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (913,'Virus', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (914,'Glass', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (915,'Shakira', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (916,'IKEA', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (917,'Batman', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (918,'Instagram', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (919,'Message', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (920,'FriendZone', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (921,'Google', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (922,'Church', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (923,'Mapa', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (924,'Keep', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (925,'TripAdvisor', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (926,'Fake News', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (927,'Buffet', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (928,'Video', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (929,'Sex', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (930,'Salad', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (931,'Recycle', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (932,'Text', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (933,'Mosquito', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (934,'Guitar', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (935,'Tambourine', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (936,'Condom', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (937,'Tree', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (938,'Planet', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (939,'Earth', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (940,'Berry', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (941,'Mars', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (942,'USB', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (943,'Angelina Jolie', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (944,'Cristiano Ronaldo', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (945,'Boxing', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (946,'Window', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (947,'Microsoft', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (948,'Sun', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (949,'Moon', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (950,'Music', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (951,'Marvel', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (952,'Supermarket', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (953,'Hole', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (954,'Milk', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (955,'Cheese', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (956,'New york', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (957,'Square', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (958,'Barber s', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (959,'Printer', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (960,'Shoe', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (961,'Chaos', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (962,'Parking', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (963,'Call', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (964,'Fire', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (965,'Fuel', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (966,'Ads', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (967,'Rainbow', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (968,'Traffic lights', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (969,'Goal', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (970,'McDonalds', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (971,'Bike', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (972,'Light', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (973,'Dark', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (974,'Door', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (975,'Mirror', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (976,'Bet', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (977,'LeBron James', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (978,'Fly', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (979,'Cookies', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (980,'Spider', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (981,'Hair', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (982,'Card', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (983,'Beer', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (984,'Laboratory', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (985,'University', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (986,'Pirates of the Caribbean', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (987,'James Bond', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (988,'Rome', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (989,'Christopher Nolan', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (990,'Labyrinth', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (991,'IA', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (992,'Competition', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (993,'Demon', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (994,'Wi-Fi', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (995,'No Condom', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (996,'Elevator', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (997,'Bill', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (998,'Mime', 'MM', 'English')");
        basedatos.execSQL("Insert into frase values (999,'DrinkGame', 'MM', 'English')");
        //Reservado hasta el 999

        //Insertar Ruleta de la Suerte en Español - 1000
        basedatos.execSQL("Insert into frase values (1000,'Beben los chicos', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1001,'Beben las chicas', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1002,'Bebe el de tu izquierda', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1003,'Bebe el de tu derecha', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1004,'Beben todos', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1005,'Bebe el último en levantarse', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1006,'Beben los que tengan coche', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1007,'Mandas beber', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1008,'Bebe el primero en hablar', 'RS', 'Español')");
        basedatos.execSQL("Insert into frase values (1009,'Beben los que tengan trabajo', 'RS', 'Español')");


        //Insertar Ruleta de la Suerte en Ingles - 1010
        basedatos.execSQL("Insert into frase values (1010,'The boys drink', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1011,'Girls drink', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1012,'Drink the one on your left', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1013,'Drink the one on your right', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1014,'They all drink', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1015,'Drink the last to rise', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1016,'Those who have a car drink', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1017,'You order drink', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1018,'Drink the first to speak', 'RS', 'English')");
        basedatos.execSQL("Insert into frase values (1019,'Those who have work drink', 'RS', 'English')");

        //Insertar Cinco Cosas en Español - 1100
        basedatos.execSQL("Insert into frase values (1100,'5 marcas de coches', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1101,'5 países europeos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1102,'5 best seller', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1103,'5 canciones que se pueden bailar', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1104,'5 géneros de películas', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1105,'5 géneros de música', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1106,'5 bebidas azucaradas', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1107,'5 videojuegos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1108,'5 jugadores de futbol históricos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1109,'5 deportistas medallistas de oro en JJOO', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1110,'5 animales domésticos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1111,'5 equipos de futbol', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1112,'5 películas de Disney Pixar', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1113,'5 series originales de Netflix', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1114,'5 prendas de vestir', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1115,'5 filósofos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1116,'5 monumentos históricos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1117,'5 capitales del mundo', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1118,'5 ciudades de Europa', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1119,'5 muebles de IKEA', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1120,'5 nombres de chica', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1121,'5 nombres de chico', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1122,'5 objetos que se pueden meter en una mochila', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1123,'5 palabras que contengan la letra E', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1124,'5 tipos de dinosaurios', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1125,'5 personajes históricos', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1126,'5 frutas', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1127,'5 verduras', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1128,'5 redes sociales', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1129,'5 cosas que te puedes encontrar en una cocina', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1130,'5 cosas que te puedes encontrar en un baño', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1131,'5 marcas de móviles', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1132,'5 comidas que lleven o puedan llevar tomate', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1133,'5 presidentes de países del mundo (Actuales)', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1134,'5 secciones que te puedes encontrar en un periódico', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1135,'5 asignaturas de la escuela', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1136,'5 fechas históricas', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1137,'5 restaurantes de comida rápida', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1138,'5 cosas que se pueden meter en un armario', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1139,'5 cosas que se pueden guardar en un maletero del coche', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1140,'5 regalos para San Valentín', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1141,'5 tipos de maquillaje', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1142,'5 elementos de la tabla periódica', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1143,'5 marcas de ropa deportiva', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1144,'5 legumbres', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1145,'5 cosas que no dirías a tu madre', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1146,'5 objetos para que juegue un perro', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1147,'5 cosas que necesitas para sobrevivir', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1148,'5 cosas que necesitas para sobrevivir un apocalipsis zombie', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1149,'5 cosas que te puedes encontrar en un avión', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1150,'5 cosas que has aprendido recientemente', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1151,'5 cosas que nunca encuentres', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1152,'5 cosas que le dirías a Donald Trump', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1153,'5 cosas que no te tragarías', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1154,'5 cosas que cambiarias si pudieras volver atrás', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1155,'5 cosas que se utilizan para quitar la nieve', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1156,'5 superhéroes de MARVEL', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1157,'5 cosas que siempre quisiste de pequeño', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1158,'5 cosas por las que te sientes agradecido', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1159,'5 cosas que te gustaría ver', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1160,'5 cosas que no se deben gritar en una discoteca', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1161,'5 cosas que te llevas en la maleta de vacaciones', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1162,'5 cosas que harías para ligarte a alguien', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1163,'5 tipos de sabores', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1164,'5 cosas que son más difíciles de lo que parecen', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1165,'5 cosas que no debes hacer cuando estés borracho', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1166,'5 cosas que te gustaría hacer', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1167,'5 cosas que no harías si estas desnudo', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1168,'5 cosas que pasan una vez en la vida', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1169,'5 cosas que harías si fueras una mosca', 'CC', 'Español')");
        basedatos.execSQL("Insert into frase values (1170,'5 minijuegos de DrinkGames', 'CC', 'Español')");
        //Reservado hasta 1199


        //Insertar Cinco Cosas en English - 1200
        basedatos.execSQL("Insert into frase values (1200,'5 car brands', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1201,'5 European countries', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1202,'5 best seller', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1203,'5 songs that can be danced', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1204,'5 movie genres', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1205,'5 genres of music', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1206,'5 sugary drinks', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1207,'5 videogames', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1208,'5 historical soccer players', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1209,'5 athletes gold medalists in the Olympic Games', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1210,'5 pets', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1211,'5 soccer teams', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1212,'5 Disney Pixar movies', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1213,'5 Netflix original series', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1214,'5 clothing', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1215,'5 philosophers', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1216,'5 historical monuments', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1217,'5 capitals of the world', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1218,'5 cities in Europe', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1219,'5 IKEA furniture', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1220,'5 girl names', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1221,'5 boy names', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1222,'5 objects that can be put in a backpack', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1223,'5 words containing letter E', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1224,'5 types of dinosaurs', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1225,'5 historical figures', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1226,'5 fruts', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1227,'5 vegetables', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1228,'5 social networks', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1229,'5 things you can find in a kitchen', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1230,'5 things you can find in a bathroom', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1231,'5 mobile brands', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1232,'5 foods that have or may include tomato', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1233,'5 presidents of countries of the world (current)', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1234,'5 sections that you can find in a newspaper', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1235,'5 school subjects', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1236,'5 historical dates', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1237,'5 fast food restaurants', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1238,'5 things that can be put in a closet', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1239,'5 things that can be stored in a car trunk', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1240,'5 gifts for Valentines Day', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1241,'5 types of makeup', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1242,'5 elements of the periodic table', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1243,'5 brands of sportswear', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1244,'5 legumes', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1245,'5 things you wouldnt say to your mother', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1246,'5 objects for a dog to play', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1247,'5 things you need to survive', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1248,'5 things you need to survive a zombie apocalypse', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1249,'5 things you can find on a airplane', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1250,'5 things you have learned recently', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1251,'5 things you never find', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1252,'5 things you would say to Donald Trump', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1253,'5 things you wouldnt swallow', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1254,'5 things you would change if you could go back', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1255,'5 things used to remove snow', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1256,'5 MARVEL superheroes', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1257,'5 things you always wanted as a child', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1258,'5 things you are grateful for', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1259,'5 things you would like to see', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1260,'5 things not to shout at a nightclub', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1261,'5 things you take in your suitcase on vacation', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1262,'5 things you would do to hook up with someone', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1263,'5 types of flavors', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1264,'5 things that are more difficult than they seem', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1265,'5 things you should not do when you are drunk', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1266,'5 things you would like to do', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1267,'5 things you would not do if you are naked', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1268,'5 things that happen once in a lifetime', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1269,'5 things you would do if you were a fly', 'CC', 'English')");
        basedatos.execSQL("Insert into frase values (1270,'5 minigames from Drink Games', 'CC', 'English')");
        //Reservado hasta 1299
        
    }

    @Override
    public void onUpgrade(SQLiteDatabase basedatos, int versionAntigua, int versionNueva) {

        basedatos.execSQL("DROP TABLE IF EXISTS frase");
        onCreate(basedatos);

    }

}
